general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
  monitor =
  color = rgb(232733)
  blur_passes = 2
  blur_size = 6
  noise = 0.0117
  contrast = 1.1
  brightness = 0.9
  vibrancy = 0.2
}

label {
  monitor =
  text = cmd[update:1000] date +"%H:%M"
  color = rgba(eceff4ff)
  font_size = 72
  font_family = JetBrainsMono Nerd Font
  position = 0, 90
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] date +"%A, %B %d"
  color = rgba(d8dee9ff)
  font_size = 28
  font_family = JetBrainsMono Nerd Font
  position = 0, 20
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 220, 60
  outline_thickness = 3
  dots_size = 0.2
  dots_spacing = 0.35
  dots_center = true
  outer_color = rgba(d580ffff)
  inner_color = rgba(2b3040ee)
  font_color = rgba(eceff4ff)
  check_color = rgba(8fbcbbff)
  fail_color = rgba(bf616aff)
  fade_on_empty = false
  hide_input = false
  placeholder_text =
  position = 0, -80
  halign = center
  valign = center
}
